select * from employees;

--IN
SELECT * FROM EMPLOYEES WHERE EMAIL IN ('PFAY');
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (10,40,60,70);

--NOT IN
SELECT * FROM EMPLOYEES WHERE FIRST_NAME  NOT IN ('Susan');

--LIKE
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE('%h');
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE('B%');
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE('%a%');
SELECT * FROM EMPLOYEES WHERE FIRST_NAME LIKE('_______e%');

--DUAL
SELECT 1 FROM DUAL;
SELECT SYSDATE FROM DUAL;
SELECT SYSDATE+1 FROM DUAL;
SELECT SYSDATE-1 FROM DUAL;

--ADD MONTHS
SELECT ADD_MONTHS(SYSDATE,5) FROM DUAL;
SELECT ADD_MONTHS (SYSDATE,-5) FROM DUAL;

--MONTHS BETWEEN
SELECT MONTHS_BETWEEN(SYSDATE,'17-06-2025') FROM DUAL;

SELECT ROUND(MONTHS_BETWEEN('20-07-2025','17-07-2024'),1) FROM DUAL;

--NEXT DAY
SELECT NEXT_DAY(SYSDATE,1) FROM DUAL;

--LAST DAY
SELECT LAST_DAY(SYSDATE) FROM DUAL;

--DATA TYPE

--TO CHAR
SELECT TO_CHAR(SYSDATE,'DD-MONTH-YY') FROM DUAL;

--TO DATE
SELECT TO_DATE('20-07-2025') FROM DUAL;

SELECT TO_CHAR(TO_DATE('30-03-2004'),'DAY') FROM DUAL;

--GENERAL FUNCTIONS
--GREATEST
SELECT GREATEST(1,2,3,4) FROM DUAL;
--LOWEST
SELECT LEAST(1,2,3,4) FROM DUAL;

SELECT EMAIL,UPPER(EMAIL),LOWER(EMAIL),INITCAP(EMAIL) FROM EMPLOYEES;

--SUBSTRING
SELECT FIRST_NAME,SUBSTR(FIRST_NAME,3,2) FROM EMPLOYEES;

--INSTRING
SELECT FIRST_NAME,INSTR(FIRST_NAME,'E',1,1) FROM EMPLOYEES;
SELECT FIRST_NAME,INSTR(FIRST_NAME,'l',2) FROM EMPLOYEES;
SELECT FIRST_NAME,INSTR(FIRST_NAME,'n',6,1) FROM EMPLOYEES;

--LENGTH
SELECT FIRST_NAME,EMAIL,LENGTH(FIRST_NAME,EMAIL) FROM EMPLOYEES;

--REVERSE
SELECT FIRST_NAME, REVERSE(FIRST_NAME) FROM EMPLOYEES;

--REPLACE
SELECT FIRST_NAME,REPLACE(FIRST_NAME,'e') FROM EMPLOYEES;

SELECT FIRST_NAME,REPLACE(FIRST_NAME,'Ellen','KING') FROM EMPLOYEES;

--TRANSLATE
SELECT FIRST_NAME,TRANSLATE(FIRST_NAME,'e','a') FROM EMPLOYEES;
SELECT FIRST_NAME,TRANSLATE(FIRST_NAME,'ab','bc') FROM EMPLOYEES;
--PAD

--RPAD(RIGH TPAD)
SELECT FIRST_NAME,RPAD(FIRST_NAME,'10','-') FROM EMPLOYEES;
--LPAD-LEFT PAD
SELECT FIRST_NAME, LPAD(FIRST_NAME,'6','-') FROM EMPLOYEES;

--TRIM 
SELECT FIRST_NAME,TRIM(' HELLO WORLD' ) FROM EMPLOYEES;

--RTRIM
SELECT FIRST_NAME,RTRIM('XXXX HELLO WORLD XXXX','X') FROM EMPLOYEES;

--LEFT TRIM
SELECT FIRST_NAME,LTRIM('XXXX HELLO WORLD XXXX','X') FROM EMPLOYEES;

--SIGN
SELECT SIGN (0) FROM DUAL;
SELECT SIGN(1) FROM DUAL;
SELECT SIGN(-1) FROM DUAL;

--MOD
SELECT MOD(5,2) FROM DUAL;

--CONTROL STATEMENTS
SELECT DEPARTMENT_ID FROM EMPLOYEES;
--DECODE
SELECT DEPARTMENT_ID,DECODE(DEPARTMENT_ID,10,'A',20,'B','X') FROM EMPLOYEES;
--CASE
SELECT DEPARTMENT_ID,
CASE 
WHEN DEPARTMENT_ID = 10 THEN 'A'
WHEN DEPARTMENT_ID = 20 THEN 'B'
ELSE 'X'
END
FROM EMPLOYEES;

select * from employees;


--GROUP
SELECT MANAGER_ID,COUNT(FIRST_NAME)
FROM EMPLOYEES
GROUP BY MANAGER_ID;


--ORDERBY
SELECT * FROM EMPLOYEES
ORDER BY JOB_ID,DEPARTMENT_ID,MANAGER_ID;

--WHERE
SELECT * FROM
EMPLOYEES
WHERE  DEPARTMENT_ID =90
ORDER BY HIRE_DATE DESC;

--HAVING
SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME,DEPARTMENT_ID,ROUND(AVG(SALARY),0) AS AVG_AMT
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID,FIRST_NAME
ORDER BY ROUND(AVG(SALARY),0) DESC;

select first_name,employee_id from employees where department_id=90;
