CREATE TABLE SALES1(
BNAME VARCHAR2(20),
BAMOUNT NUMBER(10) );

INSERT ALL INTO SALES1 VALUES
('ECITY-1',1000)
INTO SALES1 VALUES('HSR',5000)
INTO SALES1 VALUES('ECITY-2',5000)
INTO SALES1 VALUES('ECITY-1',6000)
INTO SALES1 VALUES('HSR',7000)
INTO SALES1 VALUES('HSR',7000)
INTO SALES1 VALUES('ECITY-2',10000)
SELECT * FROM DUAL;

SELECT * FROM SALES1;

SELECT BNAME ,SUM(BAMOUNT) AS TOTAL_AMT
FROM SALES1
GROUP BY BNAME
HAVING SUM(BAMOUNT) >=15000
ORDER BY SUM(BAMOUNT)
;

--SET OPERATORS

CREATE TABLE s01
(
ID number(1),
NAME VARCHAR2(10)
);

CREATE TABLE s02
(
ID number(1),
NAME VARCHAR2(10)
);

select * from s01;
select * from s02;

insert all
into s01 values(1,'A')
into s01 values(2,'B')
into s01 values(3,'C')
SELECT * FROM DUAL;

insert all
into s02 values(1,'A')
into s02 values(4,'B')
into s02 values(5,'C')
SELECT * FROM DUAL;

SELECT * FROM S01
UNION
SELECT * FROM S02;

SELECT * FROM S01-- UNION ALL COMBINE TWO TABLE 
UNION ALL
SELECT * FROM S02;


SELECT * FROM S01
INTERSECT 
SELECT * FROM S02;

--IN MINUS THE COMMON RECORD WIILL ELEMINATED (FROM THE FIRST TABLE IT REMOVE COMMON VALUES)
SELECT * FROM S01
MINUS
SELECT * FROM S02;
--IT REMOVE THE COMMON RECORD FROM SO2 TABLE
SELECT * FROM S02
MINUS
SELECT * FROM S01;
















