--EMPLOYEES TABLE ,DEPARTMENTS,EMPID,EMP FIRSTNAME,DEPARTN ID ,DEPARTNAME
--107 EMP
--27 IN DEP
--CHECK THE COUNT OF THE COUNTT IN EVERY TABLE

--TASK 1
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

--EMPLOYEE_ID,FIRST_NAME,DEPARTMENT_ID,DEPARTMENT_NAME;

--INNER JOIN
SELECT E.EMPLOYEE_ID,
        E.FIRST_NAME,
        E.DEPARTMENT_ID,D.
        DEPARTMENT_NAME,
COUNT(*) OVER (PARTITION BY E.DEPARTMENT_ID) AS EMP_COUNT_IN_DEPT,
  COUNT(*) OVER () AS TOTAL_JOINED_ROWS
        FROM 
    EMPLOYEES  E
    FULL JOIN 
    DEPARTMENTS  D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT COUNT(*)
FROM EMPLOYEES E
FULL JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--LEFT JOIN
SELECT E.EMPLOYEE_ID,E.FIRST_NAME,E.DEPARTMENT_ID,D.DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID ;

SELECT COUNT(*) FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


--RIGHT JOIN
SELECT E.EMPLOYEE_ID,E.FIRST_NAME,E.DEPARTMENT_ID,D.DEPARTMENT_NAME
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--FULL JOIN
SELECT E.EMPLOYEE_ID,E.FIRST_NAME,E.DEPARTMENT_ID,D.DEPARTMENT_NAME
FROM EMPLOYEES E
FULL JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--SELF JOIN
SELECT E1.FIRST_NAME AS EMPLOYEE,E2.FIRST_NAME AS MANAGER
FROM EMPLOYEES E1 
JOIN EMPLOYEES E2
ON E1.MANAGER_ID = E2.EMPLOYEE_ID;

SELECT E1.FIRST_NAME AS EMPLOYEE,E2.FIRST_NAME AS MANAGER
FROM EMPLOYEES E1 
JOIN EMPLOYEES E2
ON E1.MANAGER_ID = E2.EMPLOYEE_ID
WHERE E1.FIRST_NAME = 'Lisa';


SELECT
  E.EMPLOYEE_ID,
  E.FIRST_NAME,
  E.DEPARTMENT_ID,
  D.DEPARTMENT_NAME,
  COUNT(*) OVER () AS TOTAL_JOINED_ROWS
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


SELECT * FROM EMPLOYEES;
SELECT SALARY,COUNT(SALARY)
FROM EMPLOYEES
GROUP BY SALARY
ORDER BY SALARY DESC;

SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME,HIRE_DATE,SALARY,DENSE_RANK()OVER(ORDER BY SALARY DESC) AS SALARY FROM EMPLOYEES;

SELECT FIRST_NAME,HIRE_DATE,SALARY,COUNT(SALARY)FROM 
EMPLOYEES
GROUP BY FIRST_NAME,HIRE_DATE,SALARY,SALARY
HAVING SALARY BETWEEN 12000 AND 21111
ORDER BY SALARY DESC;

SELECT SALARY,ROW_NUMBER() OVER (ORDER BY SALARY DESC) FROM EMPLOYEES;

SELECT FIRST_NAME,LEAD(FIRST_NAME,1,'a') OVER(ORDER BY FIRST_NAME) AS LEAD FROM EMPLOYEES;


SELECT RIGHT('abcdefg', 3) AS Extracted from dual;
















--EMPLOYEES TABLE ,DEPARTMENTS,EMPID,EMP FIRSTNAME,DEPARTN ID ,DEPARTNAME
--107 EMP
--27 IN DEP
--CHECK THE COUNT OF THE COUNTT IN EVERY TABLE












select e.employee_id,e.first_name,e.department_id,d.department_name
from employees e
inner join departments d
on e.department_id = d.department_id;





select e.first_name,e.department_id,d.department_name
from employees e
left join departments d
on e.department_id = d.department_id;


select e.first_name,e.department_id,d.department_name
from employees e
right join departments d
on e.department_id = d.department_id;


select e.first_name,e.department_id,e.salary,d.department_name
from employees e
full join departments d
on e.department_id = d.department_id;

--self join
select * from employees;


select e.first_name employee,m.first_name manager
 from employees e
 join employees m
 on e.manager_id = m.employee_id
 where e.first_name = 'Lisa' ;
 

--SELF JOIN
SELECT E1.FIRST_NAME AS EMPLOYEE,E2.FIRST_NAME AS MANAGER
FROM EMPLOYEES E1 
JOIN EMPLOYEES E2
ON E1.MANAGER_ID = E2.EMPLOYEE_ID;

SELECT E1.FIRST_NAME AS EMPLOYEE,E2.FIRST_NAME AS MANAGER
FROM EMPLOYEES E1 
JOIN EMPLOYEES E2
ON E1.MANAGER_ID = E2.EMPLOYEE_ID
WHERE E1.FIRST_NAME = 'Lisa';









---JOINS IN SQL
--JOINS IS USED TO COMBINE TWO TABLE
-- 1 INNER JOIN

CREATE TABLE COURSES2
(
CID NUMBER(10),
CNAME VARCHAR(20)
);

INSERT ALL 
INTO COURSES2 VALUES(10,'SQL')
INTO COURSES2 VALUES(20,'UNIX')
INTO COURSES2 VALUES(30,'PLSQL')
INTO COURSES2 VALUES(40,'JAVA')
SELECT * FROM DUAL;

CREATE TABLE STUDENTS1
(
SID NUMBER(10),
SNAME VARCHAR2(10),
CID NUMBER(10),
SGENDER VARCHAR(2)
);

INSERT ALL 
INTO STUDENTS1 VALUES (100,'RITHESH',10,'M')
INTO STUDENTS1 VALUES (101,'ARUN',20,'M')
INTO STUDENTS1 VALUES (102,'NEHA',50,'M')
INTO STUDENTS1 VALUES (103,'RAHUL',30,'M')
SELECT * FROM DUAL;

--INNNER JOIN
SELECT S.SID,S.SNAME,S.CID,S.SGENDER
FROM COURSES2 C 
LEFT JOIN STUDENTS1 S
ON C.CID = S.CID;

--OUTER JOIN
SELECT S.SID,S.SNAME,C.CID,S.SGENDER
FROM COURSES2  C
FULL JOIN STUDENTS1 S
ON C.CID = S.CID;


--SELF JOIN MEANS JOINS THE TABLE ITS SELF
SELECT E1.FIRST_NAME AS EMPLOYEE,E2.FIRST_NAME AS MANAGER
FROM EMPLOYEES E1 JOIN EMPLOYEES E2
ON E1.MANAGER_ID = E2.EMPLOYEE_ID;

SELECT E1.FIRST_NAME AS EMPLOYEE,E2.FIRST_NAME AS MANAGER
FROM EMPLOYEES E1 JOIN EMPLOYEES E2
ON E1.MANAGER_ID = E2.EMPLOYEE_ID
WHERE E1.FIRST_NAME = 'Alexander';


--EMPLOYEES TABLE ,DEPARTMENTS,EMPID,EMP FIRSTNAME,DEPARTN ID ,DEPARTNAME
--107 EMP
--27 IN DEP
--CHECK THE COUNT OF THE COUNTT IN EVERY TABLE 

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
































