--TCL TRANSACTION CONTROL LIMIT
--COMMIT 
--SAVE POINT MING
--ROLLBACK

--DDL COMMANDS ARE AUTO COMMANDS
--DML ARE NOT AUTO COMMANDS

CREATE TABLE TCL111(
 A NUMBER(10)
 );
 
 SELECT * FROM TCL111;
 
 INSERT INTO TCL111 VALUES(1);
 COMMIT;
 
 INSERT INTO TCL111 VALUES (2);
 INSERT INTO TCL111 VALUES(3);
 
 select * from TCL111;
 
 --ROLLBACK WHATEVER RECORD IS AFTER COMMAND THAT IS WILL BE DELETE
 
 ROLLBACK;
  INSERT INTO TCL VALUES (2);
 INSERT INTO TCL VALUES(3);
 
 
 SAVEPOINT X;
   INSERT INTO TCL VALUES (4);
 INSERT INTO TCL VALUES(5);
 
 ROLLBACK TO X;--WHATEVER RECORD ENTER AFTER X THAT WILL BE DE;ETED
 
 SELECT * FROM TCL;
 
 SAVEPOINT Y;
INSERT INTO TCL VALUES (6);
 INSERT INTO TCL VALUES(7);
 
 ROLLBACK;
 
 
 
 CREATE TABLE TB(
 A NUMBER(1)
 );
 
 INSERT INTO TB VALUES(1);
 COMMIT;
  INSERT INTO TB VALUES(2);
 INSERT INTO TB VALUES(3);
SELECT * FROM TB;
ROLLBACK;







--DCL PURELY HANDLED BY ADMINSTRATOR;
CREATE USER NADVIK  IDENTIFIED BY ADMIN;

GRANT CREATE SESSION TO NADVIK;

GRANT SELECT,INSERT,UPDATE,DELETE  ON HR.TCL TO NADVIK;
--SQL PLUS





--DCL
--DATA CONTROL LANGUAGE

--GRANT
--REVOKE
CREATE USER UNAME IDENTIFIED BY PWD;
GRANT CREATE SESSION TO UNAME;
GRANT SELECT,INSERT,UPDATE,DELETE ON HR.TNAME TO UNAME;
REVOKE SELECT,INSERT,UPDATE,DELETE ON HR.TNAME FROM UNAME;
REVOKE SELECT ON HR.TNAME FROM UNAME;
REVOKE CREATE SESSION FROM UNAME;


SELECT * FROM EMPLOYEES WHERE 
first_name = 'Neena';
--SUBQUERY
SELECT * FROM EMPLOYEES WHERE SALARY =
(select SALARY from EMPLOYEES WHERE FIRST_NAME ='Neena');

SELECT FIRST_NAME,SALARY FROM EMPLOYEES WHERE SALARY =
(select MAX(SALARY) FROM EMPLOYEES )
UNION
SELECT FIRST_NAME,SALARY FROM EMPLOYEES WHERE SALARY  =
(select MIN (SALARY)FROM EMPLOYEES );


SELECT FIRST_NAME,DEPARTMENT_ID,SALARY FROM EMPLOYEES
WHERE (DEPARTMENT_ID,SALARY )IN
(SELECT DEPARTMENT_ID ,MAX(SALARY)FROM EMPLOYEES
GROUP BY DEPARTMENT_ID);


--CTE(COMMON TABLE EXPRESSION);
WITH E AS 
(
SELECT FIRST_NAME,DEPARTMENT_ID,SALARY,DENSE_RANK()
OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) AS RK FROM EMPLOYEES)
SELECT * FROM E WHERE RK = 14;

SELECT SALARY,RANK()OVER(ORDER BY SALARY DESC) FROM EMPLOYEES;



